export const missionEnglish: Record<string, string> = {
  DOKUMENTY: "DOCUMENTS",
  Prevádzková: "Operational",
  dokumentácia: "documentation",
  "VŠETKO NA JEDNOM MIESTE": "EVERYTHING IN ONE PLACE",
  TERMÍNY: "DEADLINES",
  "Automatické stráženie": "Automatic tracking",
  "Revízia elektro": "Electrical inspection",
  "ZOSTÁVA 14 DNÍ": "14 DAYS REMAINING",
  "NIČ NEZMEŠKÁTE": "NEVER MISS A DEADLINE",
  "PREHĽAD POVINNOSTÍ": "OBLIGATIONS OVERVIEW",
  AKTUÁLNE: "UP TO DATE",
  BEZPEČNOSŤ: "SAFETY",
  "Požiarna ochrana": "Fire safety",
  "Kontrola dokumentácie": "Documentation check",
  "14 DNÍ": "14 DAYS",
  ENERGIE: "ENERGY",
  "Spotreba pod kontrolou": "Consumption under control",
  "−12.4 % OPROTI MIN. MESIACU": "−12.4% VS. LAST MONTH",
  "REVÍZIE &amp; SERVIS": "INSPECTIONS &amp; SERVICE",
  "Všetky povinnosti včas": "Every obligation on time",
  ELEKTRO: "ELECTRIC",
  SERVIS: "SERVICE",
  ŠKOLENIA: "TRAINING",
  POISTKY: "INSURANCE",
  BOZP: "H&S",
};
